version: '3'

vars:
  TMP: tmp

tasks:
  default:
    desc: List available tasks
    cmd: task --list-all

  test:
    desc: Execute tests
    deps:
      - mktmp
    cmd: go test ./... -v -cover -coverprofile={{ .TMP }}/coverage.out {{.CLI_ARGS}}

  coverage:
    desc: Shows on the browser the test coverage of the project
    cmd: go tool cover -html={{ .TMP }}/coverage.out

  test:coverage:
    desc: Execute tests and show coverage
    deps:
      - test
      - coverage

  docs:
    desc: show documentation as it will be rendered in go pkg site. It requires pkgiste to be installed
    cmd: pkgsite {{.CLI_ARGS}} .

  mktmp:
    desc: Creates default temporary directory for temp files like coverage profile.
    cmd: mkdir -p {{ .TMP }}
